logo: # add logo name
title: SWJTUSFA - 西南交通大学科幻协会
description: > # this means to ignore newlines until "baseurl:"
  欢迎来到西南交通大学科幻协会
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: 西南交通大学科幻协会  # add banner title
banner-desc:  # add banner description

# Author settings
author-pic: writer.png # your photo
author-name: 西南交通大学科幻协会 # your name
about-author: “科幻不死，铁甲依然” # about author
email: 2947861977@qq.com # your email
phone: (496)-169-6557 # your pnone number
qq: 2947861977
weixin: SWJTUSFA
weibo: 交大科幻
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link
weixin_url:  https://mp.weixin.qq.com/mp/profile_ext?action=home&amp;__biz=fiGR8u1985eaLU6MtHsv==&amp;scene=110#wechat_redirect
weibo_url: https://m.weibo.cn/u/1900272713?from=1078095010&wm=20005_0002&sourceType=qq&uid=3254849462
github_url: https://github.com/swjtuSFA/swjtuSFA.github.io

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]